version: '3.9'

services:
  client:
    platform: linux/x86_64
    build:
      context: client
    environment:
      PORT: 3000
      API_URL: http://server:8080
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    platform: linux/x86_64
    build:
      context: server
    environment:
      PORT: 8080
    volumes:
      - ./server:/go/src/app